<a href="https://colab.research.google.com/github/120mayank/Addition/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#MAYANK KUMAR
#18SCSE1050014
#Machine Learning
#CLOUD-1


#1 Unary Operators

import numpy as np
arr = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]],

                         [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print("largest elements:",arr.max())
print("row wise maximum :",arr.max(axis=1))
print("Column wise minimum elements:",arr.min(axis=0))
print("Sum of all array elements:",arr.sum()) 
print("Commutative sum along each row:\n",arr.sum())

largest elements: 7
row wise maximum : [[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]
Column wise minimum elements: [[0 1 2 3]
 [4 5 6 7]]
Sum of all array elements: 84
Commutative summ along each row:
 84


In [4]:
#2 Numpy Implementation and creation 1-D array

import numpy as np
a=np.array([2,4,7])
print(a)

[2 4 7]


In [28]:
#3 Creation of array in numpy with various techniques

a=np.array([[3,5,7],[6,3,8]],dtype='float')
print("Array created using passed list:\n ",a)
print("-----------------------------------------------------")

b=np.array((3,7,4))
print("\nArray created using passed touple:\n",b)
print("-----------------------------------------------------")

c=np.zeros((5,6))
print("\nAn array initialized with all zeros:\n",c)
print("-----------------------------------------------------")

d=np.full((3,3),9,dtype='complex')
print("\nAn array initilized with all 6s.Array type is complex:\n",d)
print("------------------------------------------------------")

e=np.random.random((3,3))
print("\nA random array:\n",e)
print("------------------------------------------------------")

f=np.arange(0,30,8)
print("\nA sequential array with steps of 7:\n",f)
print("---------------------------------------------------------")

g=np.linspace(0,6,11)
print("\nASequential array with 10 value between 0 and 6:\n",g)
print("------------------------------------------------------")

arr=np.array([[1,2,3,4],[5,6,7,8],[4,6,8,3]])
newarr=arr.reshape(2,2,3)
print("\nOrignal array:\n",arr)
print("Reshaped array:\n",newarr)
print("--------------------------------------------------------")

arr=np.array([[1,2,3],[4,5,6]])
fl_array=arr.flatten()
print("\n Original array:\n",arr)
print("\n Fattened array:\n,",fl_array)


Array created using passed list:
  [[3. 5. 7.]
 [6. 3. 8.]]
-----------------------------------------------------

Array created using passed touple:
 [3 7 4]
-----------------------------------------------------

An array initialized with all zeros:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
-----------------------------------------------------

An array initilized with all 6s.Array type is complex:
 [[9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j]]
------------------------------------------------------

A random array:
 [[0.56609074 0.84980092 0.25813266]
 [0.03992089 0.47226052 0.31507122]
 [0.9954284  0.88736833 0.67482491]]
------------------------------------------------------

A sequential array with steps of 7:
 [ 0  8 16 24]
---------------------------------------------------------

ASequential array with 10 value between 0 and 6:
 [0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4 6. ]
--------------

In [8]:
#4 Get the number of dimensions,shape,and size of n-D array

import numpy as np
arr=np.array([[5,8,6],[7,3,9]])
print(arr)
print("Array is of type:",type(arr))
print("No of dimensions:",arr.ndim)
print("Shape of array:",arr.shape)
print("Size of array:",arr.size)
print("Array stores elements of type:",arr.dtype)


[[5 8 6]
 [7 3 9]]
Array is of type: <class 'numpy.ndarray'>
No of dimensions: 2
Shape of array: (2, 3)
Size of array: 6
Array stores elements of type: int64


In [1]:
#5 Binary Operators

import numpy as np
a=np.array([[7,5],
              [9,3]
              
])
b=np.array([[7,4],
            [3,5]])
print("Array Addition:\n",a + b)
print("Array Multiplication:\n",a * b)
print("matrix multiplication:\n",a.dot(b))


Array Addition:
 [[14  9]
 [12  8]]
Array Multiplication:
 [[49 20]
 [27 15]]
matrix multiplication:
 [[64 53]
 [72 51]]


In [33]:
#6 Checking array indexing with Slicing,Integer array indexing,Boolen array indexing

import numpy as np
arr=np.array([[-1,2,0,4],
              [4,-0.5,6,0],
              [2.6,0,7,8],
              [3,-7,4,2.0]])
# Slicing array
temp=arr[:2,::2]
print("Array with first 2 rows  and alternate columns(0 and 3):\n",temp)

#Integer array indexing example
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\n Elements at indices(0,3,(1,2),(2,1),(3,0):\n",temp)

#Boolen array indexing example
cond = arr>0 #cond is a boolean array
temp=arr[cond]
print("\nElements greater than 0:\n",temp) 






Array with first 2 rows  and alternate columns(0 and 3):
 [[-1.  0.]
 [ 4.  6.]]

 Elements at indices(0,3,(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]
